### PR TITLE
Argentina11

### PR DESCRIPTION
**Pull request by Brian393**
@modulitos 
@goldpbear 

Hello Luke and Trevor, I hope you are both well, with a little more depth of meaning than usual!

What has ultimately happened with Mapseed? Sometime we should have a talk about possible futures. In the meantime, here's a PR. Let me know how you're doing, but whenever you feel like it. I am OK so far.... best, Brian

### CODE REVIEW

**Comment by goldpbear** [comment]
Hi @Brian393! Thanks for the PR. I will get this merged/deployed this weekend.

We are doing well-- there have been some changes on our end, but I'll follow up separately to catch you up.

Hope the virus has not been too disruptive for you so far!

**Comment by Brian393** [comment]
Hello Trevor!

Thanks for answering. I am fine so far, we did cancel a residency at the
Max Planck Institute in Berlin though  - thankfully, it would have been
terrible to be in transit when everything got serious.

My friends in Argentina are, or were, ready to start a new phase of their
work, although they too will be heavily disrupted. So I am curious what
your outlook is, where you expect Mapseed to go over the middle term and
whether or how we might expect to collaborate with you in the future. It
has been a good ride so far!

all the best, stay safe, Brian

**Comment by goldpbear** [comment]
Ah, sorry to hear you had to cancel some events. Sounds like it was for the best, though.

I've deployed this PR, plus I sent you an email with some more details/thoughts about where things are at.

**Comment by Brian393** [comment]
Brilliant! And thank you. I am glad to hear that you are in Madison, maybe
we'll meet IRL some day. It's good to have a steady job when everything
else starts falling apart!

I think that in order to go ahead with Argentina 2.0, we would need a
couple hours of your time, for which we would obviously be glad to offer
some dollars - IF that were feasible for you. It's some css in the navbar
(I tried and apparently failed with some of that) and then most
importantly, that right-hand menu is getting long and my friends would like
to see some subheaders in there. So it would be one relatively short
customization on your part, and then an occasional PR from my side. I
understand that might not be feasible for you, so just let me know. If you
like I can supply a precise description.

Whew, it's snowing out and I feel lucky to be working at my home desk!

best, Brian

**Comment by goldpbear** [comment]
Hey @Brian393 -- we should sync on the requirements for Argentina 2.0 at some point. I think it's likely we can find some time to push out some updates to keep that project moving forward.

**Pull request merged**
