### PR TITLE
Argentina18

### PR DESCRIPTION
**Pull request by Brian393**
@goldpbear 

Hello Trevor, here is a PR for the Argentina map - a new Capa de analisis.

Hope you are doing well, surviving all the madness.

best, Brian

### CODE REVIEW

**Comment by goldpbear** [comment]
@Brian393 -- looks good! I'll get this merged and deployed later on this evening.

**Comment by goldpbear** [comment]
Deployed!

**Comment by Brian393** [comment]
That's cool Trevor. Thank you! This map continues to deliver, a whole new
crop of people are using it down there. I was really stunned to see this
post:

https://mapa.casarioarteyambiente.org/report/8844

What it shows is the source of the Rio Branco - right where it wells up
from the ground. It was made by Brazilians from the very remote Istituto
Gaia, whom we showed how to use the map by teleconference during the early
days of the pandemic.

I also see that you must have set up a selector to restore the zoom and
orientation buttons while still preserving the hamburger icon for mobile
phone menus, that was really nice of you, thank you, I was struggling to do
that and I ran out of time before figuring out how.

Hope you are as well as the present circumstances allow!

all the best from Chicago, Brian

**Comment by goldpbear** [comment]
Glad to hear it! Yes, that post is impressive and the new layers look nice as well.

Yeah, we had an issue with the icons on the map controls that I'm hoping is resolved now. I'm also realizing that some of the popups with large content do not scroll and certain content is getting clipped. I will look into that this weekend...

**Pull request merged**
