### PR TITLE
Argentina16

### PR DESCRIPTION
**Pull request by Brian393**
@goldpbear 

Here's the last before our seminar - best, Brian

### CODE REVIEW

**Comment by goldpbear** [comment]
@Brian393 -- it looks like this PR has some outstanding conflicts. Would it be possible to resolve those?

**Comment by Brian393** [comment]
I will definitely give it a try! I noticed that but I have never had to do
it before. Let me look, it is something I should learn how to do.

best, BH

**Comment by goldpbear** [comment]
Ok, let me know if you have questions. I'm not sure why the conflicts are showing up, but I think you may need to sync your fork with the main mapseed repo.

**Comment by Brian393** [comment]
Yes that was it, my bad as they say. If you don't mind I am just going to
abandon that branch and send a new pull request.

**Comment by goldpbear** [comment]
Yep-- no worries!

**Pull request closed without merging**
