### PR TITLE
Convert "Hey Duwamish" image into text

### PR DESCRIPTION
**Pull request by zmbc**
Resolves issue #259.

### CODE REVIEW

**Comment by zmbc** [comment]
Any update on this?

**Comment by goldpbear** [comment]
Any reason we shouldn't go ahead and merge this?

**Comment by LukeSwart** [comment]
@ghostwave made our current HeyDuwamish logo, which was based off the HeyArnold font. I had the chance to talk with him, and his recommendation was to use svg or just keep it as a png. Sorry that this issue was poorly defined :-(

It seems that he made some tweaks to the image after creating it from the font, so maybe we can either keep the png, or use an svg instead?

**Comment by zmbc** [comment]
> Use png or svg

So... what does that mean? The whole *point* of this PR was to replace a png with text. If I "use png," the diff will be 0 lines long :laughing:

As I read it, you're basically saying that the change we thought we wanted to make, we don't actually want to make. If that's the case, just close the PR and issue.

**Comment by LukeSwart** [comment]
Sorry about this confusion - I didn't know that the designer of the original logo had made changes to the HeyArnold font. Looks like we found that out during the implementation, and I wasn't able to confirm that with the designer until recently (he is really hard to get a hold of)

I was leaving this issue open in case someone wants a approve the changes to the logo that this PR makes. But I think you're right - I'll just close the issue, because it seems out of scope.

I appreciate your effort in implementing this PR - I think it will come in handy for other flavors/branding. Anyone who is looking to build their branding off of a specific font, or looking to cater to screen readers, will find this PR handy.

**Pull request closed without merging**
