### PR TITLE
Argentina20

### PR DESCRIPTION
**Pull request by Brian393**
@goldpbear 

Hello Trevor -
I have made a few simple changes described in the commit.
However my repo is no longer up to date with yours. I even tried freshly cloning the Mapseed repo, but I am still not up to date on the cloned master (I can see things that differ from the online version). Maybe you work off some other branch?
I think this might have happened because you did not send a pull request back to me last time. Or more likely, it's something I just don't understand about git.
Sorry for any inconvenience, Brian

### CODE REVIEW

**Comment by goldpbear** [comment]
Hey @Brian393 -- thanks for another contribution! That's strange about the differences between your fork and the main repo. Nothing has changed deployment-wise AFAIK (everything is deployed off the `master` branch).

I noticed there are a couple of conflicts in the PR-- I'm happy to resolve those, and maybe we can deploy the changes on this PR to the staging site for this flavor and inspect any differences.

As for differences between they deployed site and the local version, I wonder if this is another instance of custom CSS changes not taking due to the way class names are dynamically created in production. If so, I can work on incorporating the custom CSS changes like we did before.

**Comment by Brian393** [comment]
On Fri, Oct 23, 2020 at 6:09 AM Trevor Croxson <notifications@github.com>
wrote:

> As for differences between they deployed site and the local version, I
> wonder if this is another instance of custom CSS changes not taking due to
> the way class names are dynamically created in production. If so, I can
> work on incorporating the custom CSS changes like we did before.
>
Hello Trevor -

Thanks for answering! For sure the whole thing is a bit mysterious to me:
when I run the site locally I do not see certain CSS changes (the controls
at upper left are all white) but online it looks fine, so don't worry about
it. Next time I will start from your master branch and presumably there
will not be any merge conflicts. I was just thrown off by this difference.

Also, no need to bother with the staging site, it's more trouble than it's
worth. All I did was add two custom icons and shift some geojsons over to
the server in Argentina. That makes it easy to gradually add features to
one of our "Capa de analísis" layers - they can just change the geojsons
and we don't have to bother you. In a few weeks I will set up another one
like that, hopefully without the merge conflicts....

Hope you're well with all the political and medical craziness in this
country! Stay safe,

all the best, Brian

**Comment by goldpbear** [comment]
Hey Brian-- I've got the conflicts resolved and the changes deployed up to production. I think everything looks ok, but let me know if anything still isn't right and I'll push up fixes.

Thanks, and stay safe!

**Comment by Brian393** [comment]
It's perfect Trevor, thanks very much!

I'll probably be back in a couple weeks with a new analysis layer. The map
is still a hit down there...

best, Brian

**Comment by goldpbear** [comment]
Sounds good-- I'll keep an eye out :)

**Pull request merged**
